# .astro/config.yaml (modifié)
project:
  name: mlops-project-survivor
deployments:
  - name: dev
    executor: celery
    image:
      name: quay.io/astronomer/astro-runtime:7.3.0
    env: dev
    volumes:
      - ./include:/usr/local/airflow/include
      #- C:/Users/Administrateur/AppData/Roaming/gcloud:/home/astro/.config/gcloud:ro
